### ISSUE TITLE
Add tutorials about using C++ modules

### ISSUE THREAD

**Issue by aminya** [kelteseth/arewemodulesyet#25]
One of the reasons it has been hard for people to adopt modules is that there are few practical tutorials on how to do it.

For example, modules make this possible for CMake (used by fmt)
https://github.com/vitaut/modules

It would be useful to add these resources to the website.

**Comment by ChuanqiXu9** [comment]
BTW, while this may not be best for beginners, clang provides some guidelines about transiting a project to modules: https://clang.llvm.org/docs/StandardCPlusPlusModules.html#transitioning-to-modules

**Comment by cristianadam** [comment]
[A gentle introduction to C++ Modules](https://medium.com/@guilhermeprogrammer/a-gentle-introduction-to-c-modules-29bbcf7ac86f) is a starter point.

[C++20 modules and Boost: an analysis](https://anarthal.github.io/cppblog/modules) and [C++20 modules and Boost: deep dive](https://anarthal.github.io/cppblog/modules2) is another story.

Lastly [C++20 Modules, CMake, And Shared Libraries](https://crascit.com/2024/04/04/cxx-modules-cmake-shared-libraries/) covers a more advanced topic.

**Comment by ChuanqiXu9** [comment]
Thanks. I've added it here: https://arewemodulesyet.org/documents/
