### ISSUE TITLE
Flux library has modules support

### ISSUE THREAD

**Issue by cristianadam** [kelteseth/arewemodulesyet#9]
As reported by the author at https://www.reddit.com/r/cpp/comments/1cdtabj/comment/l1ixxtk/ 

Since currently we only have 2 (two) libraries, having a 50% increase is something! 😀

**Comment by kelteseth** [comment]
Nice 💪 we just removed about 1000 years of wait time a7bf06670a215a2bf5d23d678550debe39adeae7
